### ISSUE TITLE
失效(BUG)

### ISSUE THREAD

**Issue by nekobzd** [xh321/LiteLoaderQQNT-Directly-Jump#1]
## 概述
请使用`Github Issue Label`功能标记你的ISSUE类型（BUG还是新功能提议等）

<并请在下面详细描述你的ISSUE内容或建议>
在QQNT9.9.1环境下失效 点击后跳转至"当前网页非官方页面"

<完毕/>

在提交前确认以下事项：

- [√] 已更新到最新版本
- [√] 没有重复或相似的ISSUE
- [] 若是BUG，该问题不是由母插件`BetterQQNT`导致的（若不能确定请不用勾选）
- [√] 若是BUG，该问题不是由`QQNT`导致的（若不能确定请不用勾选）

## 重现步骤（可选）

1. 步骤1
安装插件
2. 步骤2
输入未知网址
3. 步骤3
点击网页跳转
   

## 当前行为（可选）
若可以，请附带截图
![43698f2adc0cee9d80b6538f327d3066](https://github.com/xh321/LiteLoaderQQNT-Directly-Jump/assets/134399582/cfaee23b-2708-4330-99f7-1cfbf272e28c)

## 期望行为
可以附带草图

## 修复建议
若你知道如何修复，可以贴上修复的代码

## 附件
其他需要额外说明的内容或文件

> ```
> 日志内容
> ```

**Comment by nekobzd** [comment]
抱歉 可能是复制的时候点错了 导致步骤一后多了一张图片 请无视

**Comment by xh321** [comment]
能否提供一下9.9.1的安装包？从官网和检查更新均无法获取。最新版目前是9.9.0-14619。

**Comment by xh321** [comment]
是否是安装了QQNTim？目前已经更新做了兼容

**Comment by xh321** [comment]
如果没有问题的话，先关闭ISSUE了，还有问题欢迎随时reopen。
