### ISSUE TITLE
大佬有兴趣开发一个点击视频直接以系统播放器播放视频的插件吗，QQNT自带的播放器太难用了🤣🤣

### ISSUE THREAD

**Issue by Sunsh4j** [xh321/LiteLoaderQQNT-Directly-Jump#2]

**Comment by xh321** [comment]
应该，可以，没问题！

**Comment by Sunsh4j** [comment]
> 应该，可以，没问题！

好的，多谢您🧡🧡🧡

**Comment by Sunsh4j** [comment]
> 应该，可以，没问题！

大佬，这个还有戏吗🤣🤣

**Comment by xh321** [comment]
> > 应该，可以，没问题！
> 
> 大佬，这个还有戏吗🤣🤣

我只是最近有点忙，晚上就给你写一个

**Comment by Sunsh4j** [comment]
> > > 应该，可以，没问题！
> > 
> > 
> > 大佬，这个还有戏吗🤣🤣
> 
> 我只是最近有点忙，晚上就给你写一个

没事没事，我也不急，你先忙你的就是了🤣🤣
只是刚才又被QQNT自带的播放器给蠢哭了，才想起来来这问问🤣🤣

**Comment by xh321** [comment]
> > > > 应该，可以，没问题！
> > > 
> > > 
> > > 大佬，这个还有戏吗🤣🤣
> > 
> > 
> > 我只是最近有点忙，晚上就给你写一个
> 
> 没事没事，我也不急，你先忙你的就是了🤣🤣 只是刚才又被QQNT自带的播放器给蠢哭了，才想起来来这问问🤣🤣

绷不住了，笑死

**Comment by xh321** [comment]
> > > > 应该，可以，没问题！
> > > 
> > > 
> > > 大佬，这个还有戏吗🤣🤣
> > 
> > 
> > 我只是最近有点忙，晚上就给你写一个
> 
> 没事没事，我也不急，你先忙你的就是了🤣🤣 只是刚才又被QQNT自带的播放器给蠢哭了，才想起来来这问问🤣🤣

是不是那个脑瘫播放器，下面的进度条经常会冒出来挡住内容

**Comment by Sunsh4j** [comment]
> 

这是一方面，还有就是前进后退不好控制，也没法循环

**Comment by xh321** [comment]
https://github.com/xh321/LiteLoaderQQNT-Media-Local-View

**Comment by Sunsh4j** [comment]
> https://github.com/xh321/LiteLoaderQQNT-Media-Local-View

OK，试了下，很不错，还有开关！
不过，有个小问题是：视频在已保存到本地的状态下，双击聊天界面里的视频上的任意位置，都可以唤醒播放器。如果是未下载，则需要先点击下载按钮（双击聊天界面里的视频上的任意位置没有反应），或者双击下载按钮，会先下载，然后唤醒播放器播放。
所以能否在未下载的状态下，**双击视频的任意位置就可以下载**，然后在下载完成后唤醒播放器播放

**Comment by xh321** [comment]
> > https://github.com/xh321/LiteLoaderQQNT-Media-Local-View
> 
> OK，试了下，很不错，还有开关！ 不过，有个小问题是：视频在已保存到本地的状态下，双击聊天界面里的视频上的任意位置，都可以唤醒播放器。如果是未下载，则需要先点击下载按钮（双击聊天界面里的视频上的任意位置没有反应），或者双击下载按钮，会先下载，然后唤醒播放器播放。 所以能否在未下载的状态下，**双击视频的任意位置就可以下载**，然后在下载完成后唤醒播放器播放

最终我做成单击了。因为单击可以同时触发下载和播放，但是双击只会触发下载，而不会开始播放。下一个版本马上发布~

**Comment by xh321** [comment]
> > > https://github.com/xh321/LiteLoaderQQNT-Media-Local-View
> > 
> > 
> > OK，试了下，很不错，还有开关！ 不过，有个小问题是：视频在已保存到本地的状态下，双击聊天界面里的视频上的任意位置，都可以唤醒播放器。如果是未下载，则需要先点击下载按钮（双击聊天界面里的视频上的任意位置没有反应），或者双击下载按钮，会先下载，然后唤醒播放器播放。 所以能否在未下载的状态下，**双击视频的任意位置就可以下载**，然后在下载完成后唤醒播放器播放
> 
> 最终我做成单击了。因为单击可以同时触发下载和播放，但是双击只会触发下载，而不会开始播放。下一个版本马上发布~

缺点就是，正常的视频点一下也开始播放了，不过我觉得没什么很大问题

**Comment by Sunsh4j** [comment]
> 

可以的，就是操作逻辑和平常的不太一样需要记一下，习惯就好了，基本没啥问题

**Comment by xh321** [comment]
> > 
> 
> 可以的，就是操作逻辑和平常的不太一样需要记一下，习惯就好了，基本没啥问题

已经更新了，0.1.1版本
