### ISSUE TITLE
在config.json中自定义浏览器不起作用

### ISSUE THREAD

**Issue by shibuyameltdown** [xh321/LiteLoaderQQNT-Directly-Jump#3]
不编辑该文件的情况下，默认浏览器是chrome，但是点击链接会在qq浏览器打开；
编辑该文件后（如图），还是qq浏览器打开
![QQ_1723302052045](https://github.com/user-attachments/assets/bf56153e-1b69-4934-af77-57250f92cfc5)

**Comment by shibuyameltdown** [comment]
qq版本：9.9.12-25765 (64位)
插件版本：0.1.3

**Comment by xh321** [comment]
请仔细阅读readme

→修改文件中的 `browser` 字段为你的浏览器可执行文件完整路径

所以你应该写
```
{
  "browser":"C:\\XXXXX"
}
```

**Comment by shibuyameltdown** [comment]
> 请仔细阅读readme
> 
> →修改文件中的 `browser` 字段为你的浏览器可执行文件完整路径
> 
> 所以你应该写
> 
> ```
> {
>   "browser":"C:\\XXXXX"
> }
> ```

💀这样啊，感谢
